name: animated_transitions_example
description: "Demonstrates how to use the animated_transitions package."

version: 1.0.6+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  animated_transitions: ^1.0.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 