name: animated_transitions
description: "A collection of beautiful transitions to navigate between pages in a Flutter app."
version: 0.0.1
homepage: https://github.com/your_name/your_repo
repository: https://github.com/your_name/your_repo

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
